### ISSUE TITLE
Odd behavior of MOSM for single-output

### ISSUE THREAD

**Issue by zhh210** [GAMES-UChile/mogptk#15]
When there is only one output, I was expecting MOSM to behave comparably with SM. However, when I tried it out on the [notebook](https://github.com/GAMES-UChile/mogptk/blob/master/examples/03_Parameter_Initialization.ipynb), replacing SM to MOSM makes the performance deteriorated a lot (cell [10]). The only thing I've changed is in cell [5]:
`model = mogptk.SM([data], Q=3) ---> model = mogptk.MOSM(data, Q=3)`

Replacing SM by SM_LMC can still give very similar performance though. Is this behavior expected or am I misused MOSM? Thanks.

**Comment by Ale-Cuevas** [comment]
I think there is 2 reasons why it could be giving that results:
-There is a bug in the initialization in MOSM that was fixed in the develop branch, that could be causing problems.
-In the MOSM initialization, the spectral variance is multiplied by a factor 2 to prevent falling in local minima when optimizing, that means that it needs more iterations to reach the same results as SM (the example only uses 100 iterations), by using more iterations i was able to achieve similar results with both SM and MOSM.

**Comment by zhh210** [comment]
Thanks @Ale-Cuevas , it looks like due to the first reason. Also I noticed that using SM to initialize a MOSM may fail with an error about Cholesky decomposition. Probably because the features are of very different scale however BNSE is fine. But this would be another topic.
