### ISSUE TITLE
Problems with initializing parameters

### ISSUE THREAD

**Issue by Swagur** [GAMES-UChile/mogptk#22]
Hello,

I get this error when I run the ```model.init_parameters()``` command.
![image](https://user-images.githubusercontent.com/60924893/98693935-3016a880-2371-11eb-950a-182f98fd2640.png)
I tried all three methods but I get the error everytime. First I worked with some toy data, but I also get this error when I run the _example_single_output_spectral_mixture_ example. 
I saw there was an issue about the 'BNSE' method being fragile and you were improving the library, but I think this is a different issue.
Do you know how I could solve this error, or is this problem going to be solved in the improved library?

Thanks in advance!

**Comment by tdewolff** [comment]
Can you verify if this works when you explicitly set the default positive minimum for GPflow? Try `gpflow.config.set_default_positive_minimum(1e-6)` and see if that fixes the problem. Otherwise I'm afraid the initialization method is unable to find peaks in the spectral signal, resulting in `None` being returned. This might mean that initialization doesn't work on your data set, but I think we should properly test for that case and throw a meaningful error.

In any case, the improved version of MOGPTK will fix all these issues!

**Comment by tdewolff** [comment]
This issue should have been solved in the new v0.2.0 version (written using PyTorch). Please let me know if you still run into trouble.
