### ISSUE TITLE
Multi-tasking regression and classification problems

### ISSUE THREAD

**Issue by ChihYuLee** [GAMES-UChile/mogptk#62]
Dear contributor, 

I am recently using this toolkit. However, my multi-task project is handling one regression problem and a multi-class classification problem. None of the models works well. I would suppose the current functions don't support classification. I would appreciate if you could suggest any way to modify the kernels and likelihoods to facilitate this type of classification problem

Best, 
CY

**Comment by tdewolff** [comment]
Hi Chih Yu Lee,

In order to use classification you have to use the underlying GPR package.
I've just created an example of two channels, each with a different
likelihood (Bernoulli and StudentT's), which shows you how to do a simple
classification problem. I hope that helps!

https://games-uchile.github.io/mogptk/examples.html?q=08_Multi_Likelihood_Classification

Saludos cordiales,
Taco de Wolff

**Comment by ChihYuLee** [comment]
Dear all,

Thank you for making this into an example. I appreciate it, and I will let
you know if I run into further issue.

Best,
CY
